### ISSUE TITLE
建议针对每一个文件返回上传结果，方便处理上传状态，让用户容易辨识

### ISSUE THREAD

**Issue by magiccode1412** [4444TENSEI/AlistUploader.js#1]
**遇到的问题**
在大文件传输时，当进度达到100%时，其实还是未完成状态，需要等待一段时间，才会完成并弹出警告提示完成，容易造成用户以为依旧完成并直接关闭网页，导致上传失败

**建议**
对每一个完成上传的文件，返回一个状态，方便通过js对前端页面中传输状态做出修改，让用户更容易知道是否上传完成

例如下面这个，在接收到单文件传输状态码时，可以修改为已完成或者上传失败

![image](https://github.com/user-attachments/assets/cabd8f29-c812-4740-90d8-942c499d67a4)

**Comment by 4444TENSEI** [comment]
## 对于上传进度不准确的问题，正在寻找一个合适的替代方案

1. 目前的上传进度是基于客户端(XMLHttpRequest(XHR)对象的`progress`事件)来反馈的，这导致了上传进度不够精确。
2. 对于`无法获取服务端上传进度`这点可以直接在`Alist客户端`进行手动测试，可以发现Alist客户端自身的进度条反馈本身就是失效的，故暂时只能在v0.1.2版本采用客户端计算上传进度。

## 经过接口测试，怀疑Alist服务端并未返回任务进度，参照官方接口文档

1. 获取任务id

​	https://alist-v3.apifox.cn/api-128101260

2. 根据任务id获取进度等信息

​	https://alist-v3.apifox.cn/api-142468741

3. 获取未完成/已完成的任务进度

​	https://alist-v3.apifox.cn/api-128101295



经过上方接口测试发现，上传状态并不会被服务端捕捉到，这导致了无法获取具体的服务端上传进度，具体问题还要一些时间去解决，寻找是否存在实际的上传进度反馈接口。

## 关于实际的上传完成状态反馈

在源码中已实现，具体参考位置：https://github.com/4444TENSEI/AlistUploaderJS/blob/3a72180084b89d8f71b0ec260123fd067ce7ce26/src/v0.1.2/alist-uploader.js#L283

```
// 触发complete事件，传递allSuccess表示是否所有文件都上传成功
this.trigger("complete", allSuccess);
```

在后续版本应该会优化一下，在多文件上传时，追踪每个文件各自的完成状态返回单独的上传状态。

- 可以在前端页面中使用这种方式监听：

```
// 监听上传完成事件
alistUploaderOptions.on("complete", (allSuccess) => {
  if (allSuccess) {
    alert("所有文件上传完成！");
  } else {
    alert("部分文件上传失败。");
  }
});
```

*虽然**上传进度暂时无法从服务端获取**，但是**上传完成的反馈**是**基于服务器响应**的。(当服务器成功处理完上传请求并返回响应后，`XMLHttpRequest` 的 `load` 事件会被触发，表明服务器已经接收了文件，并且上传过程已经完成，因此比较可靠。*)

**Comment by 4444TENSEI** [comment]
于[v0.1.3版本](https://github.com/4444TENSEI/AlistUploaderJS/releases/tag/0.1.3)中完成
